name: Cita Checker

on:
  schedule:
    - cron: '*/10 * * * *'   # every 10 minutes
  workflow_dispatch:

jobs:
  run-checker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies for Chrome
        run: sudo apt-get update && sudo apt-get install -y libnss3 libgconf-2-4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install selenium requests

      - name: Install Chrome + compatible ChromeDriver
        uses: browser-actions/setup-chrome@v1
        with:
          chrome: stable
          chromedriver: true

      - name: Check Chrome versions
        run: |
          google-chrome --version
          chromedriver --version

      - name: Run cita checker script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python cita_checker.py
