name: cita_checker

on:
  workflow_dispatch: # allows manual trigger
  schedule:
    - cron: "*/10 * * * *" # every 10 minutes

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install selenium requests python-telegram-bot

      - name: Run cita checker
        run: |
          python your_script.py
