name: Cita Checker

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  run-checker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium requests

      - name: Install Chrome + ChromeDriver
        uses: browser-actions/setup-chrome@v1
        with:
          chrome: stable
          chromedriver: true

      - name: Chrome version
        run: google-chrome --version

      - name: ChromeDriver version
        run: chromedriver --version

      - name: Run cita checker script with debug
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          set -x
          python cita_checker.py
